### ISSUE TITLE
Not working on Firefox 67

### ISSUE THREAD

**Issue by hellocatfood** [gandalf3/BlendExchanger#1]
Trying to use this plugin on Firefox 67 on Ubuntu and the Blend-Exchange button doesn't show up in the editor window.

**Comment by kitt-cat** [comment]
Indeed. I'm planning to do a rewrite soon to go with the upcoming blend-exchange update. Currently the script depends on jquery, which it has no need to and is very likely related to why it's not working.

**Comment by kitt-cat** [comment]
Fixed by 20ed15fef8a2f8265d550d0308ae3d39c95133e5.

**Comment by kitt-cat** [comment]
@hellocatfood Note that there are currently some [issues](https://github.com/GiantCowFilms/Blend-Exchange/issues/43) with the interaction with the old (but still currently in use) blend exchange which will be fixed when the new blend exchange is rolled out.
